kind: pipeline
name: default

steps:
  - name: Build & Deploy
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket'ini bağla
    commands:
      - docker build -t myapp .    # Docker image'ı oluştur
      - docker run -d --name go-server -p 8080:8080 myapp  # Docker container'ı başlat
