kind: pipeline
name: default

steps:
- name: golangci-lint
  image: golangci/golangci-lint:latest
  commands:
    - golangci-lint run --enable=all --verbose ./...  # Çoklu linter'lar ile kodu analiz et
