kind: pipeline
name: default

steps:
- name: golangci-lint
  image: golangci/golangci-lint:latest
  commands:
    - golangci-lint run --enable=golint --enable=errcheck --enable=staticcheck --verbose ./...
