kind: pipeline
name: default

steps:
  - name: test
    image: golang
    commands:
      - go mod tidy  # Bağımlılıkları temizler ve günceller
      - go test

  - name: build
    image: golang
    commands:
      - go mod tidy  # Bağımlılıkları temizler ve günceller
      - go build -o output

  - name: run
    image: golang
    commands:
      - ./output  # Eğer build kısmında çalıştırılabilir dosyayı üretip çıkarttıysanız
