kind: pipeline
name: default

steps:
  - name: Test
    image: golang:1.23
    commands:
      - go mod download
      - go test ./... -v

  - name: Linter
    image: golangci/golangci-lint:v1.54.2
    commands:
      - golangci-lint run ./...

  - name: Build & Run
    image: golang:1.23
    commands:
      - go mod download
      - go build -o myapp .
      - docker build -t my-go-app .
      - docker run -d --name go-app my-go-app
