kind: pipeline
name: default

steps:
  - name: Build & Deploy
    image: docker:latest
    commands:
      - docker build -t myapp .
      - docker run -d --name go-server -p 8080:8080 myapp
